### ISSUE TITLE
Format Watermark Text

### ISSUE THREAD

**Issue by saelco** [saurabh-m-w/image_watermark#2]
I'm using long text and get overlap watermark text on image. Is there any function to format watermark text like size, width, background color, etc?

**Comment by Agamjot13Singh** [comment]
What are you trying to do? Why do you need such a long watermark? Are you trying to add text to the image (NO WATERMARK)?
You should check out https://pub.dev/packages/flutter_painter

**Comment by Fahim227** [comment]
I solved the problem by editing in source code. The problem was the text size was fixed and not dynamic for every size of image. I solved that editing the source code.

**Comment by Fahim227** [comment]
> > I solved the problem by editing in source code. The problem was the text size was fixed and not dynamic for every size of image. I solved that editing the source code.
> 
> Nice, thanks for your efforts. I would recommend you to open a PR

I created a PR.

**Comment by MohammedJunaidNew** [comment]
The problem was the text size was fixed and not dynamic for every size of image @Fahim227  Could  you pls share some of code to understand for change the font size in watermark text ?
